### ISSUE TITLE
Add D-REPR representation for TopoFlow files

### ISSUE THREAD

**Issue by dgarijo** [mintproject/ModelCatalog#40]
This is the file shared by @binh-vu for RTS files (precipitation):
```
version: "2"
resources:
  data:
    type: np-bin
    dtype: float64
attributes:
  data: $.data
semantic_model:
  mint:Variable:1:
    properties:
      - [rdf:value, data]
    static_properties:
      - [mint:standardName, atmosphere_water__rainfall_volume_flux]
  prefixes:
    mint: https://mint.isi.edu/ 
```
The questions remaining are: how to use it to drive the transformations?
